version: "3.9"

services:
  airflow:
    image: apache/airflow:2.2.3-python3.8
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./data_pipeline:/opt/airflow/dags

  minio:
    image: bitnami/minio:latest
    command: server /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data

  neo4j:
    image: neo4j:4.4.2
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data

  spark-master:
    image: bitnami/spark:3.2.0
    environment:
      - SPARK_MODE=master

  spark-worker:
    image: bitnami/spark:3.2.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  spark-worker-2:
    image: bitnami/spark:3.2.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"

volumes:
  minio-data:
  neo4j-data:

networks:
  network:
